server:
  port: 8090
spring:
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: ${spring.servlet.multipart.max-file-size}
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: 3.38.93.50
      port: 6379
      password: ON_SECRET
  datasource:
    url: jdbc:h2:./db;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver